import type { Metadata } from 'next';
import { type GiftCodeStatus, getGiftCodeStatus } from '@/app/premium/actions';
import GiftPageClient from './GiftPageClient';

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || 'https://interchat.dev';

// Helper to format tier name for display
function formatTierName(tier: string): string {
  return `Inter${tier.charAt(0)}${tier.slice(1).toLowerCase()}`;
}

// Generate metadata for Discord rich embeds and SEO
export async function generateMetadata(props: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id: codeId } = await props.params;
  const giftStatus = await getGiftCodeStatus(codeId);

  // Base metadata for invalid/not found/claimed codes
  if (giftStatus.status !== 'valid') {
    const titles: Record<Exclude<GiftCodeStatus['status'], 'valid'>, string> = {
      not_found: 'Gift Code Not Found',
      claimed: 'Gift Already Claimed',
    };
    const descriptions: Record<
      Exclude<GiftCodeStatus['status'], 'valid'>,
      string
    > = {
      not_found: "This gift code doesn't exist or is invalid.",
      claimed: 'This gift code has already been redeemed.',
    };

    return {
      title: `${titles[giftStatus.status]} | InterChat`,
      description: descriptions[giftStatus.status],
      openGraph: {
        title: titles[giftStatus.status],
        description: descriptions[giftStatus.status],
        type: 'website',
        url: `${BASE_URL}/gift/${codeId}`,
        siteName: 'InterChat',
      },
      twitter: {
        card: 'summary',
        title: titles[giftStatus.status],
        description: descriptions[giftStatus.status],
      },
      other: {
        'theme-color': '#ef4444', // Red for error states
      },
    };
  }

  // Valid gift code - show enticing embed
  const tierName = formatTierName(giftStatus.tier);
  const title = `You've received a ${tierName} gift!`;
  const description = giftStatus.isFree
    ? `Claim your free ${tierName} premium subscription and unlock exclusive features!`
    : `You've been gifted a discounted ${tierName} subscription. Claim it now!`;

  return {
    title: `${title} | InterChat`,
    description,
    openGraph: {
      title,
      description,
      type: 'website',
      url: `${BASE_URL}/gift/${codeId}`,
      siteName: 'InterChat',
      // Note: OG image is automatically generated by opengraph-image.tsx
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      // Note: Twitter image is automatically generated by opengraph-image.tsx
    },
    other: {
      'theme-color': '#7B61FF', // Purple theme for premium gifts
    },
  };
}

export default async function GiftPage(props: {
  params: Promise<{ id: string }>;
}) {
  const { id: codeId } = await props.params;
  const initialStatus = await getGiftCodeStatus(codeId);

  return <GiftPageClient codeId={codeId} initialStatus={initialStatus} />;
}
